image: registry.gitlab.com/python-devs/ci-images:active

stages:                 # List of stages for jobs, and their order of execution
  - build
  - test
  - build-artifact

build-job:              # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Setup the environment..."
    - python3.12 -V
    - python3.12 -m venv tmp/venv
    - source tmp/venv/bin/activate
    - pip install -r requirements.txt



unittest-job:           # This job runs in the test stage.
  stage: test           # It only starts when the job in the build stage completes successfully.
  script:
    - echo "This job tests something"
    - ls -a
    - python -m unittest tests/unittest/test_put_item_method.py


integration-test-job:   # This job also runs in the test stage.
  stage: test           # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo "This job tests something"

build-artifact-job:     # This job runs in the build-artifact stage.
  stage: build-artifact # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "archive lambda_function"