image: python:3.9-alpine

stages:                 # List of stages for jobs, and their order of execution
  - build
  - test
  - build-artifact

build-job:              # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Setup the environment..."
    - python3.9 -V
    - python3.9 -m venv tmp/venv
    - source tmp/venv/bin/activate
    - pip install -r requirements.txt

unittest-job:           # This job runs in the test stage.
  stage: test           # It only starts when the job in the build stage completes successfully.
  script:
    - echo "This job tests something"
    - python3.9 -m venv tmp/venv
    - source tmp/venv/bin/activate
    - pip install -r requirements.txt
    - python3.9 -m unittest tests/unittest/test_put_item_method.py

build-artifact-job:     # This job runs in the build-artifact stage.
  stage: build-artifact # It only runs when *both* jobs in the test stage complete successfully.
  before_script:
    - apk add --update zip
  script:
    - echo "archive lambda_function"
    - python3.9 -m venv tmp/venv
    - source tmp/venv/bin/activate
    - pip install -r requirements.txt
    - deactivate
    - ls -a
    - cd /builds/personal-projects841140/user-stories-processor/tmp/venv/lib/python3.9/site-packages
    - zip -r ../../../../../my_deployment_package.zip .
    - cd ../../../../../
    - zip -ur my_deployment_package.zip application
    - zip -ur my_deployment_package.zip business
    - zip -ur my_deployment_package.zip data_access
    - zip -ur my_deployment_package.zip tests
    - zip -ur my_deployment_package.zip lambda_function.py
    - zip -ur my_deployment_package.zip requirements.txt
    - ls -a
    - mkdir build_output
    - echo "Build artifact content" > build_output/my_deployment_package.zip
  artifacts:
    paths:
      - build_output/my_deployment_package.zip
    expose_as: 'My Build Artifact'
