test_record_include_all_fields = {'Records': [{'eventID': '2c245b237b5f7b15223a9cb3dff7662a',
                                               'eventName': 'INSERT',
                                               'eventVersion': '1.1',
                                               'eventSource': 'aws:dynamodb',
                                               'awsRegion': 'us-east-1',
                                               'dynamodb': {'ApproximateCreationDateTime': 1750788513.0,
                                                            'Keys': {'user_story_id': {'S': 'd4436e50-07e9-42f5-870f-657aa9116af2'}},
                                                            'NewImage': {'summary': {'S': 'text'},
                                                                         'project_id': {'S': '34'},
                                                                         'sprint': {'S': '67'},
                                                                         'issue_type': {'S': '45'},
                                                                         'description': {'S': 'text'},
                                                                         'reporter': {'S': '678'},
                                                                         'assignee': {'S': '67'},
                                                                         'labels': {'L': [{'S': 'new'}, {'S': 'task'}]},
                                                                         'user_story_id': {'S': 'd4436e50-07e9-42f5-870f-657aa9116af2'}},
                                                            'SequenceNumber': '588833200000776554551948791',
                                                            'SizeBytes': 195,
                                                            'StreamViewType': 'NEW_AND_OLD_IMAGES'},
                                               'eventSourceARN': 'arn:aws:dynamodb:us-east-1:784455852728:table/UserStories/stream/2025-03-25T15:43:21.293'}]}


test_record_missing_fields = {'Records': [{'eventID': '7338c980420d3d5d5d267fb1ddcad890',
                                           'eventName': 'INSERT',
                                           'eventVersion': '1.1',
                                           'eventSource': 'aws:dynamodb',
                                           'awsRegion': 'us-east-1',
                                           'dynamodb': {'ApproximateCreationDateTime': 1750788039.0,
                                                        'Keys': {'user_story_id': {'S': '92256d43-ecc3-4e90-a49c-eb1d133714de'}},
                                                        'NewImage': {'summary': {'S': 'text'},
                                                                     'description': {'S': 'text'},
                                                                     'user_story_id': {'S': '92256d43-ecc3-4e90-a49c-eb1d133714de'}},
                                                        'SequenceNumber': '588815500002027003775819987',
                                                        'SizeBytes': 124,
                                                        'StreamViewType': 'NEW_AND_OLD_IMAGES'},
                                           'eventSourceARN': 'arn:aws:dynamodb:us-east-1:784455852728:table/UserStories/stream/2025-03-25T15:43:21.293'}]}
